### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by bnb** [cutenode/good-first-issue#122]
I've gotten this a couple times recently. If anyone wants to tackle, feel free ❤️ 

```
$ good-first-issue

? Choose a project: debugger.html
(node:89426) UnhandledPromiseRejectionWarning: HttpError: Validation Failed
    at /Users/cyren/GitHub/good-first-issue/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async search (/Users/cyren/GitHub/good-first-issue/lib/search.js:18:20)
    at async Command.<anonymous> (/Users/cyren/GitHub/good-first-issue/bin/good-first-issue.js:45:20)
(node:89426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
 catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:89426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DanielRuf** [comment]
Needs some try / catch block. I'll check that.

**Comment by DanielRuf** [comment]
> Needs some try / catch block. I'll check that.

This is not the case anymore as you already wrap the whole in a try / catch an return the error object. I think this can be closed.

**Comment by DanielRuf** [comment]
See https://github.com/cutenode/good-first-issue/blob/e456412c24df153b90fb0c2c0b9a43c84fffbad3/bin/good-first-issue.js#L28 and https://github.com/cutenode/good-first-issue/blob/41f30ce9f296336194fed7d077b0ace5846458c9/bin/good-first-issue.js#L29

**Comment by vivekkachare** [comment]
Hi! I'd like to work on this issue and investigate the unhandled
promise rejection coming from the GitHub API request. 
I'll submit a PR once I have a fix.
